title: jhw96의 블로그
description: 꾸준히 계속
author: jhw96
avatar: /profile.png
email: ds6tvi@naver.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
#
# google_analytics:

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
#
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================

logo: profile.png
social:
  name: Hyeonwoong Jang
  links:
    - https://www.facebook.com/profile.php?id=ds6tvi%40naver.com
    - https://github.com/ngzhio
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
